"""add new tables (Tag, Blog, BlogTag)

Revision ID: a5cbac85881c
Revises: be5c9a9690c2
Create Date: 2024-12-20 11:52:01.118350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5cbac85881c'
down_revision: Union[str, None] = 'be5c9a9690c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
